### ISSUE TITLE
tsc reports error on using `style` on `FileDrop`

### ISSUE THREAD

**Issue by farfromrefug** [probablykasper/svelte-tauri-filedrop#1]
If i remove `FileDrop.svelte.d.ts` then it works.
<img width="1018" alt="Screenshot 2022-03-22 at 15 27 25" src="https://user-images.githubusercontent.com/655344/159505220-4d406cce-6338-4e9b-b971-98bd03decf1c.png">

Edit: in fact removing the `FileDrop.svelte.d.ts` does not fix it!

**Comment by probablykasper** [comment]
What's the full error? How exactly are you running tsc, and what's your tsconfig?

**Comment by farfromrefug** [comment]
the error is through vscode using svelte code extension. and the error is 100% normal seeing the component typings does not inherit div component.
i am not in front of computer but the error is pretty simple. `style` is not a prop of FileDrop.
i will share the tsconfig but it makes no difference.

**Comment by probablykasper** [comment]
Ah right, I didn't notice you're passing a `style` property to `<FileDrop>` itself. `<FileDrop>` doesn't actually contain any elements, it's purely a `<slot />`, so it can't have a `style` property.

Check out [overlay.svelte](https://github.com/probablykasper/svelte-tauri-filedrop/blob/e13e9473d5b6b9c2b3805ee25c677ef47a8e1f4f/src/routes/overlay.svelte) for an example of how to use it as an overlay
