### ISSUE TITLE
Question: Limit drop to an area

### ISSUE THREAD

**Issue by MassivDash** [probablykasper/svelte-tauri-filedrop#2]
Hello, 
I was wondering if there is a possibility to limit the dropzone to an area ?

For example having multipule filedrops components on the page results in all dropzone fields fired at once. 
I tried to catch a html ondrop event in svelte in hopes to tie area to the filedrop event but it seems that tauri blocks it.

**Comment by probablykasper** [comment]
Unfortunately not, tauri doesn't have a way to do that yet :/

See https://github.com/tauri-apps/tauri/issues/3063
